"""Show tool middleware for Mambo Agent.

Intercepts ``show`` tool calls, reads the target file from the backend,
persists it via ``FileService``, and returns structured metadata in the
``ToolMessage``.  The UI layer (``MamboAgentBuiltinToolProvider``) picks
up the result and emits a ``FILE`` sub-message for frontend display.
"""

import json
from pathlib import PurePosixPath
from typing import Callable, Literal

from langchain.agents.middleware.types import AgentMiddleware
from langchain_core.messages import ToolMessage
from langchain_core.tools import StructuredTool
from langgraph.prebuilt.tool_node import ToolCallRequest
from pydantic import BaseModel, Field

from mambo_agents.backends.protocol import BackendProtocol, _get_mime_type
from mambo_agents.backends.schemas import VirtualPath
from sqlalchemy.ext.asyncio import AsyncSession

from backend.schemas.enums import FileManagementType
from backend.services.file_service import FileService


class ShowInput(BaseModel):
    """Args schema for the ``show`` tool."""

    path: str = Field(description="文件虚拟路径，例如 /workspace/image.png")
    mode: Literal["Normal", "Mini_Avatar", "Gal_Avatar", "Group", "Spark"] = Field(
        default="Normal",
        description=(
            "Display mode for the file:\n"
            "- Normal: default inline file display\n"
            "- Mini_Avatar: use image as conversation AI avatar\n"
            "- Gal_Avatar: pin image to left side above toolbar, push AI messages right\n"
            "- Group: group consecutive File images, allow user to pin one to top\n"
            "- Spark: hide all other content (text/reasoning/tools), only show Spark + Group files"
        ),
    )
    wait_timeout: int = Field(
        default=0,
        description=(
            "If the file does not exist yet, maximum seconds to wait (range 10-600). "
            "Use this when a background process (e.g. ComfyUI) is generating the file. "
            "The tool will poll every 3s and return when the file is complete. "
            "Set to 0 (default) to fail immediately if the file is not found."
        ),
        ge=0,
        le=600,
    )


_SHOW_TOOL_DESCRIPTION = (
    "Display a file (text, image, etc.) to the **human user** in the chat UI. "
    "After calling, the file appears below your message — visible to the User only, NOT to you. "
    "IMPORTANT: You will NOT receive file content; you only get back file_id, filename, mime_type. "
    "Do NOT describe or analyse file contents after show unless you already read the file first. "
    "This tool does not return image content — images are only displayed to the User.\n\n"
    "If the file is being generated by a background process (e.g. an execute command that kicked off "
    "a long-running task like ComfyUI image generation), pass wait_timeout (seconds, max 600) to wait "
    "for the file to appear. The tool will poll every 3s and return when the file is complete. "
    "If the file path is definitely wrong or the script has already failed, do NOT use wait_timeout — "
    "pass 0 and the tool will fail fast."
)


async def _download_safe(
    backend: BackendProtocol, path: str,
) -> tuple[bytes | None, str | None]:
    """Download file bytes from backend; return (content_bytes, error_str).

    Uses ``adownload_files`` (async protocol method) so that backends with
    per-instance locks (e.g. ``SshBackend._async_lock``) can serialize
    SFTP access and avoid paramiko deadlocks on concurrent calls.
    """
    try:
        results = await backend.adownload_files([VirtualPath(path)])
        if not results:
            return None, "adownload_files returned empty results"
        r = results[0]
        if r.error:
            return None, str(r.error)
        return r.content, None
    except Exception as exc:
        return None, str(exc)


class ShowMiddleware(AgentMiddleware):
    """Middleware that intercepts ``show`` tool calls.

    Reads the file from the current backend, persists it to the file store,
    and returns a JSON blob with the ``file_id`` so that the
    ``MamboAgentBuiltinToolProvider`` can create a ``FILE`` sub-message.

    Parameters
    ----------
    backend:
        The backend providing file-system operations (reads the file).
    session_factory:
        Async callable returning a fresh ``AsyncSession`` for
        ``FileService``.
    """

    def __init__(
        self,
        backend: BackendProtocol,
        session_factory: Callable[[], AsyncSession],
    ) -> None:
        super().__init__()
        self._backend = backend
        self._session_factory = session_factory

        self.tools = [
            StructuredTool.from_function(
                name="show",
                description=_SHOW_TOOL_DESCRIPTION,
                coroutine=self._ashow,
                args_schema=ShowInput,
                infer_schema=False,
            )
        ]

    # ------------------------------------------------------------------
    # Tool implementation
    # ------------------------------------------------------------------

    async def _ashow(self, path: str, mode: str = "Normal", wait_timeout: int = 0) -> str:
        """Core logic: check existence → download → persist → return metadata."""
        # 1. 先检查文件是否存在
        try:
            pp = PurePosixPath(path)
            glob_result = await self._backend.aglob(pp.name, VirtualPath(str(pp.parent)))
            file_exists = glob_result.error is None and bool(glob_result.matches)
        except Exception:
            file_exists = False

        # 2. 文件不存在 → 根据 wait_timeout 决定行为
        if not file_exists:
            if wait_timeout > 0:
                return json.dumps({
                    "status": "pending",
                    "path": path,
                    "timeout": wait_timeout,
                    "mode": mode,
                }, ensure_ascii=False)
            return json.dumps({"error": f"File not found: {path}", "mode": mode}, ensure_ascii=False)

        # 3. 文件存在 → 下载 + 持久化
        content_bytes, error = await _download_safe(self._backend, path)
        if error:
            return json.dumps({"error": error, "mode": mode}, ensure_ascii=False)

        filename = PurePosixPath(path).name
        mime = _get_mime_type(path)

        # If the content is valid UTF-8 text, treat it as text regardless of
        # file extension.  This handles files like .env, Dockerfile, or other
        # non-.txt extensions that contain plain UTF-8 text but whose MIME
        # type was guessed as application/octet-stream (or another non-text
        # type) by mimetypes / _get_mime_type.
        if content_bytes:
            sample = content_bytes[:8192]
            try:
                sample.decode("utf-8")
                # Content is valid UTF-8 → use FileUtils to resolve the proper
                # text MIME type (falling back to text/plain when the extension
                # is not in the map).
                from backend.utils.file_utils import FileUtils
                mime = FileUtils.correct_mime_type(filename, mime, sample)
            except (UnicodeDecodeError, ValueError, LookupError):
                # Not valid UTF-8 text; keep the original MIME guess and let
                # save_file_from_bytes perform its own detection / rejection.
                pass

        async with self._session_factory() as db:
            fs = FileService(db)
            db_file = await fs.save_file_from_bytes(
                data=content_bytes or b"",
                filename=filename,
                mime_type=mime,
                management_type=[FileManagementType.SUB_MESSAGE.value],
                sub_path="chat_attachments",
            )

        return json.dumps({
            "file_id": db_file.id,
            "filename": filename,
            "mime_type": mime,
            "mode": mode,
        }, ensure_ascii=False)

    # ------------------------------------------------------------------
    # Middleware hooks (delegate to default — no wrapping needed)
    # ------------------------------------------------------------------

    async def awrap_tool_call(
        self,
        request: ToolCallRequest,
        handler: Callable,
    ) -> ToolMessage:
        """Delegate to the default tool executor; all logic lives in ``_ashow``."""
        return await handler(request)
