"""v_1_2_0_7_backend

Revision ID: 04f04e99c0b8
Revises: d94821cdb39e
Create Date: 2026-03-30 17:11:23.066263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04f04e99c0b8'
down_revision: Union[str, Sequence[str], None] = 'd94821cdb39e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BackendConfig',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('backendType', sa.String(length=50), nullable=False),
    sa.Column('configData', sa.JSON(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('Agent', sa.Column('backendIds', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Agent', 'backendIds')
    op.drop_table('BackendConfig')
    # ### end Alembic commands ###
