"""v_1_2_0_5_chat_log

Revision ID: 3fba843ab7b7
Revises: c4bcadddcf78
Create Date: 2026-03-25 20:33:26.638041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '3fba843ab7b7'
down_revision: Union[str, Sequence[str], None] = 'c4bcadddcf78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MamboPostLog',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('chatId', sa.String(length=36), nullable=True),
    sa.Column('messageId', sa.String(length=36), nullable=True),
    sa.Column('managerName', sa.String(length=100), nullable=True),
    sa.Column('agentName', sa.String(length=100), nullable=True),
    sa.Column('configMetaData', sa.JSON(), nullable=True),
    sa.Column('rawPayload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_MamboPostLog_chatId'), 'MamboPostLog', ['chatId'], unique=False)
    op.create_index(op.f('ix_MamboPostLog_messageId'), 'MamboPostLog', ['messageId'], unique=False)
    op.create_index('ix_mambopostlog_created_at_desc', 'MamboPostLog', [sa.literal_column('"createdAt" DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mambopostlog_created_at_desc', table_name='MamboPostLog')
    op.drop_index(op.f('ix_MamboPostLog_messageId'), table_name='MamboPostLog')
    op.drop_index(op.f('ix_MamboPostLog_chatId'), table_name='MamboPostLog')
    op.drop_table('MamboPostLog')
    # ### end Alembic commands ###
