"""v1.1.3_baseline

Revision ID: 4442b0f1e406
Revises: 
Create Date: 2026-03-03 17:07:23.783183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4442b0f1e406'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema to v1.1.3 state."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. AIProvider
    op.create_table('AIProvider',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('apiHost', sa.String(length=255), nullable=False),
        sa.Column('apiKey', sa.String(length=255), nullable=False),
        sa.Column('use_proxy', sa.Boolean(), nullable=False, server_default='0'),
        sa.Column('worker_type', sa.String(length=50), nullable=False, server_default='openai'),
        sa.PrimaryKeyConstraint('id')
    )

    # 2. AIModel
    op.create_table('AIModel',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('modelId', sa.String(length=100), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('providerId', sa.String(length=36), nullable=False),
        sa.Column('meta_config', sa.Text(), nullable=True),
        sa.Column('model_type', sa.String(length=50), nullable=False, server_default='chat'),
        sa.ForeignKeyConstraint(['providerId'], ['AIProvider.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # 3. GlobalSettings
    op.create_table('GlobalSettings',
        sa.Column('key', sa.String(length=50), nullable=False),
        sa.Column('value', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('key')
    )

    # 4. McpServer (存在于 v1.1.3，因为后续版本引用了它)
    op.create_table('McpServer',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('transportType', sa.String(length=20), nullable=False),
        sa.Column('command', sa.String(length=255), nullable=True),
        sa.Column('args', sa.JSON(), nullable=True),
        sa.Column('env', sa.JSON(), nullable=True),
        sa.Column('url', sa.String(length=500), nullable=True),
        sa.Column('isEnabled', sa.Boolean(), nullable=True),
        sa.Column('last_status', sa.String(length=50), nullable=True),
        sa.Column('last_test_at', sa.DateTime(), nullable=True),
        sa.Column('last_error', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    # 5. File (纯净版：无 storage_type, content)
    op.create_table('File',
        sa.Column('id', sa.Text(), nullable=False),
        sa.Column('filename', sa.Text(), nullable=False),
        sa.Column('storage_path', sa.Text(), nullable=False),
        sa.Column('mime_type', sa.Text(), nullable=False),
        sa.Column('size', sa.Integer(), nullable=False),
        sa.Column('management_type', sa.JSON(), nullable=False, server_default='[]'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('storage_path')
    )

    # 6. Resource
    op.create_table('Resource',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('createdAt', sa.DateTime(), nullable=False),
        sa.Column('updatedAt', sa.DateTime(), nullable=False),
        sa.Column('itemType', sa.String(length=20), nullable=False),
        sa.Column('resourceType', sa.String(length=50), nullable=True),
        sa.Column('parentId', sa.String(length=36), nullable=True),
        sa.Column('sortOrder', sa.Integer(), nullable=False),
        sa.Column('latestVersionId', sa.String(length=36), nullable=True),
        sa.Column('kb_id', sa.String(length=36), nullable=True),
        sa.Column('kb_config', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['parentId'], ['Resource.id'], ),
        sa.ForeignKeyConstraint(['latestVersionId'], ['ResourceVersion.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # 7. ResourceVersion
    op.create_table('ResourceVersion',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('resourceId', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('sortOrder', sa.Integer(), nullable=False),
        sa.Column('commitMessage', sa.String(length=255), nullable=True),
        sa.Column('createdAt', sa.DateTime(), nullable=False),
        sa.Column('updatedAt', sa.DateTime(), nullable=False),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('attributes', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['resourceId'], ['Resource.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # 8. ResourceKBChunk
    op.create_table('ResourceKBChunk',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('resource_id', sa.String(length=36), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('chunk_index', sa.Integer(), nullable=False),
        sa.Column('byte_size', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('vector_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default='1970-01-01 00:00:00'),
        sa.Column('processed_at', sa.DateTime(), nullable=True),
        sa.Column('fts_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['resource_id'], ['Resource.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ResourceKBChunk_resource_id'), 'ResourceKBChunk', ['resource_id'], unique=False)
    op.create_index(op.f('ix_ResourceKBChunk_status'), 'ResourceKBChunk', ['status'], unique=False)

    # 9. Chat (纯净版：无 enabled_mcp_ids)
    op.create_table('Chat',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('createdAt', sa.DateTime(), nullable=False),
        sa.Column('itemType', sa.String(length=20), nullable=False),
        sa.Column('parentId', sa.String(length=36), nullable=True),
        sa.Column('sortOrder', sa.Integer(), nullable=False),
        sa.Column('lastOpenedAt', sa.DateTime(), nullable=True),
        sa.Column('systemPrompt', sa.Text(), nullable=True),
        sa.Column('modelParameters', sa.Text(), nullable=True),
        sa.Column('aiModelId', sa.String(length=36), nullable=True),
        # 注意：此处保留 resource_prompt_list，因为它是 v1.1.3 之前就存在的
        # 表结构中是 TEXT，模型中是 JSON，以表结构为准
        sa.Column('resource_prompt_list', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['aiModelId'], ['AIModel.id'], ),
        sa.ForeignKeyConstraint(['parentId'], ['Chat.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # 10. Message
    op.create_table('Message',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('createdAt', sa.DateTime(), nullable=False),
        sa.Column('role', sa.String(length=20), nullable=False),
        sa.Column('chatId', sa.String(length=36), nullable=False),
        sa.Column('sortOrder', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['chatId'], ['Chat.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # 11. SubMessage
    op.create_table('SubMessage',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('createdAt', sa.DateTime(), nullable=False),
        sa.Column('messageId', sa.String(length=36), nullable=False),
        sa.Column('sortOrder', sa.Integer(), nullable=False),
        sa.Column('type', sa.String(length=50), nullable=False),
        sa.Column('config', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(['messageId'], ['Message.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SubMessage')
    op.drop_table('Message')
    op.drop_table('Chat')
    op.drop_index(op.f('ix_ResourceKBChunk_status'), table_name='ResourceKBChunk')
    op.drop_index(op.f('ix_ResourceKBChunk_resource_id'), table_name='ResourceKBChunk')
    op.drop_table('ResourceKBChunk')
    op.drop_table('ResourceVersion')
    op.drop_table('Resource')
    op.drop_table('File')
    op.drop_table('McpServer')
    op.drop_table('GlobalSettings')
    op.drop_table('AIModel')
    op.drop_table('AIProvider')
    # ### end Alembic commands ###
