"""v_1_2_0_3_agent_init

Revision ID: 53f119eb6bc8
Revises: cfc6a5a87cc2
Create Date: 2026-03-18 15:47:37.348694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53f119eb6bc8'
down_revision: Union[str, Sequence[str], None] = 'cfc6a5a87cc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Agent',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('itemType', sa.String(length=20), nullable=False),
    sa.Column('parentId', sa.String(length=36), nullable=True),
    sa.Column('sortOrder', sa.Integer(), nullable=False),
    sa.Column('AgentType', sa.String(length=50), nullable=False),
    sa.Column('systemPrompt', sa.TEXT(), nullable=True),
    sa.Column('modelParameters', sa.JSON(), nullable=True),
    sa.Column('agentParameters', sa.JSON(), nullable=True),
    sa.Column('aiModelId', sa.String(length=36), nullable=True),
    sa.Column('agentAvatarId', sa.String(length=36), nullable=True),
    sa.Column('resourcePromptList', sa.JSON(), nullable=True),
    sa.Column('enabledMcpIds', sa.JSON(), nullable=True),
    sa.Column('subAgents', sa.JSON(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aiModelId'], ['AIModel.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parentId'], ['Agent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Agent')
    # ### end Alembic commands ###
