"""v1_2_0_1_add_chat_enabled_mcp_ids

Revision ID: 77b13d67506f
Revises: 923ee239d567
Create Date: 2026-03-12 10:29:49.378754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77b13d67506f'
down_revision: Union[str, Sequence[str], None] = '923ee239d567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Chat', sa.Column('enabled_mcp_ids', sa.JSON(), nullable=True))



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Chat', 'enabled_mcp_ids')
    # ### end Alembic commands ###
