"""v_1_2_0_4_chat_agent

Revision ID: c4bcadddcf78
Revises: 53f119eb6bc8
Create Date: 2026-03-19 16:54:40.537709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4bcadddcf78'
down_revision: Union[str, Sequence[str], None] = '53f119eb6bc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 修改点1: 添加 chatMode 时，必须提供 server_default，否则存量数据会报错
    # 假设 ChatMode.NORMAL 的值是 'NORMAL'，请根据你的枚举实际值修改
    op.add_column('Chat', sa.Column('chatMode', sa.String(length=20), nullable=False, server_default='normal'))
    op.add_column('Chat', sa.Column('agentId', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 2. 删除 agentId 列
    op.drop_column('Chat', 'agentId')

    # 3. 删除 chatMode 列
    op.drop_column('Chat', 'chatMode')

    # ### end Alembic commands ###
