"""v_1_2_0_2_add_mcptool_table

Revision ID: cfc6a5a87cc2
Revises: 77b13d67506f
Create Date: 2026-03-12 22:08:19.840183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'cfc6a5a87cc2'
down_revision: Union[str, Sequence[str], None] = '77b13d67506f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('McpTool',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('server_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('input_schema', sa.JSON(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('review_mode', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_McpTool_server_id'), 'McpTool', ['server_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_McpTool_server_id'), table_name='McpTool')
    op.drop_table('McpTool')
    # ### end Alembic commands ###
