"""v_1_2_0_6_message_tree

Revision ID: d94821cdb39e
Revises: 3fba843ab7b7
Create Date: 2026-03-26 22:16:25.058506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'd94821cdb39e'
down_revision: Union[str, Sequence[str], None] = '3fba843ab7b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Message', sa.Column('parentId', sa.String(length=36), nullable=True))
    op.add_column('Message', sa.Column('lastActiveAt', sa.DateTime(), nullable=False, server_default='2000-01-01 00:00:00'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Message', 'lastActiveAt')
    op.drop_column('Message', 'parentId')
    # ### end Alembic commands ###
